name: Reusable Builder
description: Build project for a given OS and version

inputs:
  os:
    required: true
    type: string
  version:
    required: true
    type: string

runs:
  using: composite
  steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Meson
      run: |
        python -m pip install --upgrade pip
        pip install meson
      shell: bash

    - name: Build project
      run: |
        python scripts/meson/build.py --clean
      shell: bash
      env:
        BUILD_VERSION: ${{ inputs.version }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.os }}-build-${{ inputs.version }}
        path: |
          build/
          install/