name: Install Linux Dependencies
description: Installs build-essential and ninja-build on Ubuntu
runs:
  using: "composite"
  steps:
    - run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build
      shell: bash