name: Build on macOS

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install system dependencies
      run: |
        brew update
        brew install ninja

    - name: Install Meson
      run: |
        python -m pip install --upgrade pip
        pip install meson

    - name: Build project
      run: |
        python scripts/meson/build.py --clean

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: macos-build
        path: |
          build/
          install/