name: Meson Multi-Platform Build

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Linux dependencies
        uses: ./.github/actions/install-linux-deps
      - name: Call builder
        uses: ./.github/actions/builder
        with:
          os: 'linux'
          version: ${{ needs.set-version.outputs.version }}

  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Windows dependencies
        uses: microsoft/setup-msbuild@v1
      - name: Call builder
        uses: ./.github/actions/builder
        with:
          os: 'windows'
          version: ${{ needs.set-version.outputs.version }}

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install macOS dependencies
        uses: ./.github/actions/install-macos-deps
      - name: Call builder
        uses: ./.github/actions/builder
        with:
          os: 'macos'
          version: ${{ needs.set-version.outputs.version }}