name: Reusable Builder

on:
  workflow_call:
    inputs:
      os:
        required: true
        type: string
      version:
        required: true
        type: string

jobs:
  build:
    runs-on: ${{ inputs.os == 'linux' && 'ubuntu-latest' || inputs.os == 'windows' && 'windows-latest' || 'macos-latest' }}

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install Meson
      run: |
        python -m pip install --upgrade pip
        pip install meson

    - name: Build project
      run: |
        python scripts/meson/build.py --clean
      env:
        BUILD_VERSION: ${{ inputs.version }}

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.os }}-build-${{ inputs.version }}
        path: |
          build/
          install/