name: Build All Operating Systems

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  set-version:
    uses: ./.github/workflows/set_version.yml

  build-linux:
    needs: set-version
    uses: ./.github/workflows/builder.yml
    with:
      os: 'linux'
      version: ${{ needs.set-version.outputs.version }}

  build-windows:
    needs: set-version
    uses: ./.github/workflows/builder.yml
    with:
      os: 'windows'
      version: ${{ needs.set-version.outputs.version }}

  build-macos:
    needs: set-version
    uses: ./.github/workflows/builder.yml
    with:
      os: 'macos'
      version: ${{ needs.set-version.outputs.version }}