on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  build-linux:
    runs-on: ubuntu-latest
    steps:
    - name: Install Linux dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential ninja-build
    - name: Call builder
      uses: ./.github/actions/builder
      with:
        os: 'linux'
        version: ${{ needs.set-version.outputs.version }}

  build-windows:
    runs-on: windows-latest
    steps:
    - name: Install Windows dependencies
      uses: microsoft/setup-msbuild@v1
    - name: Call builder
      uses: ./.github/actions/builder
      with:
        os: 'windows'
        version: ${{ needs.set-version.outputs.version }}

  build-macos:
    runs-on: macos-latest
    steps:
    - name: Install macOS dependencies
      run: |
        brew update
        brew install cmake ninja
    - name: Call builder
      uses: ./.github/actions/builder
      with:
        os: 'macos'
        version: ${{ needs.set-version.outputs.version }}