name: Rez Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.x'

    - name: Install Rez from source
      run: |
        git clone https://github.com/AcademySoftwareFoundation/rez.git
        cd rez
        python install.py
      shell: cmd

    - name: Build with Rez
      run: |
        python -c "import site; import os; rez_path = os.path.join(site.USER_BASE, 'Scripts', 'rez-build.exe'); os.system(f'{rez_path} .')"
      shell: cmd