name: Rez Package

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.x'

      - name: Install Rez from source
        run: |
          git clone https://github.com/AcademySoftwareFoundation/rez.git
          cd rez
          python install.py

      - name: Build with Rez
        run: rez-build .