name: Set Version

on:
  workflow_call:
    outputs:
      version:
        description: 'Generated version number'
        value: ${{ jobs.version.outputs.version }}

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}

    steps:
    - uses: actions/checkout@v4

    - name: Generate version
      id: version
      run: |
        VERSION=$(date +%Y.%m.%d)-${{ github.run_number }}
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Generated version: $VERSION"